apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: 8175-tasks
  name: 8175-tasks
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 0.0-0
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/8175-tasks-dev/8175-tasks:0.0-0
    importPolicy: {}
    referencePolicy:
      type: Source